<template>
  <div class="q-pa-md">
    <ActivityTable :columns="columns" :rows="rows" :pagination="pagination" />
  </div>
</template>

<script setup>
import { ref } from "vue";
import ActivityTable from "./ActivityTable.vue"
const pagination = ref({
  sortBy: "desc",
  descending: false,
  page: 1,
  rowsPerPage: 15,
});
const columns = [
  {
    name: "name",
    required: true,
    label: "Name",
    align: "left",
    sortable: true,
    headerStyle: "font-weight: bold",
  },
  {
    name: "type",
    align: "left",
    label: "Type",
    field: "type",
    sortable: true,
    headerStyle: "font-weight: bold",
  },

  {
    name: "createdAt",
    label: "Created At",
    align: "left",
    field: "createdAt",
    headerStyle: "font-weight: bold",
  },
  {
    name: "category",
    label: "Category",
    align: "left",
    field: "category",
    sortable: true,
    headerStyle: "font-weight: bold",
  },
  {
    name: "body",
    label: "Body",
    align: "left",
    field: "body",
    sortable: true,
    headerStyle: "font-weight: bold",
  },
  {
    name: "actions",
    label: "Actions",
    align: "center",
    field: "actions",
    headerStyle: "font-weight: bold",
  },
  // {
  //   name: "calcium",
  //   label: "Calcium (%)",
  //   field: "calcium",
  //   sortable: true,
  //   sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  // },
  // {
  //   name: "iron",
  //   label: "Iron (%)",
  //   field: "iron",
  //   sortable: true,
  //   sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  // },
];

const rows = [
  {
    name: "John Doe",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-01-01",
    category: "AML/P",
  },
  {
    name: "Jane Doe",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-02-01",
    category: "AML/P",
  },
  {
    name: "Bob Smith",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-03-01",
    category: "AML/P",
  },
  {
    name: "Alice Johnson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-04-01",
    category: "AML/P",
  },
  {
    name: "Charlie Brown",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-05-01",
    category: "AML/P",
  },
  {
    name: "Eva Martinez",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-06-01",
    category: "AML/P",
  },
  {
    name: "David Wilson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-07-01",
    category: "AML/P",
  },
  {
    name: "Grace Lee",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-08-01",
    category: "AML/P",
  },
  {
    name: "Frank Adams",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-09-01",
    category: "AML/P",
  },
  {
    name: "Sophie Turner",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-10-01",
    category: "AML/P",
  },
  {
    name: "Alice Johnson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-04-01",
    category: "AML/P",
  },
  {
    name: "Bob Smith",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-03-01",
    category: "AML/P",
  },
  {
    name: "Alice Johnson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-04-01",
    category: "AML/P",
  },
  {
    name: "Charlie Brown",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-05-01",
    category: "AML/P",
  },
  {
    name: "Eva Martinez",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-06-01",
    category: "AML/P",
  },
  {
    name: "David Wilson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-07-01",
    category: "AML/P",
  },
  {
    name: "Grace Lee",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-08-01",
    category: "AML/P",
  },
  {
    name: "Frank Adams",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-09-01",
    category: "AML/P",
  },
  {
    name: "Sophie Turner",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-10-01",
    category: "AML/P",
  },
  {
    name: "Alice Johnson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-04-01",
    category: "AML/P",
  },
  {
    name: "Bob Smith",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-03-01",
    category: "AML/P",
  },
  {
    name: "Alice Johnson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-04-01",
    category: "AML/P",
  },
  {
    name: "Charlie Brown",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-05-01",
    category: "AML/P",
  },
  {
    name: "Eva Martinez",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-06-01",
    category: "AML/P",
  },
  {
    name: "David Wilson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-07-01",
    category: "AML/P",
  },
  {
    name: "Grace Lee",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-08-01",
    category: "AML/P",
  },
  {
    name: "Frank Adams",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-09-01",
    category: "AML/P",
  },
  {
    name: "Sophie Turner",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-10-01",
    category: "AML/P",
  },
  {
    name: "Alice Johnson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-04-01",
    category: "AML/P",
  },
  {
    name: "Bob Smith",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-03-01",
    category: "AML/P",
  },
  {
    name: "Alice Johnson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-04-01",
    category: "AML/P",
  },
  {
    name: "Charlie Brown",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-05-01",
    category: "AML/P",
  },
  {
    name: "Eva Martinez",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-06-01",
    category: "AML/P",
  },
  {
    name: "David Wilson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-07-01",
    category: "AML/P",
  },
  {
    name: "Grace Lee",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-08-01",
    category: "AML/P",
  },
  {
    name: "Frank Adams",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-09-01",
    category: "AML/P",
  },
  {
    name: "Sophie Turner",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-10-01",
    category: "AML/P",
  },
  {
    name: "Alice Johnson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-04-01",
    category: "AML/P",
  },
  {
    name: "Bob Smith",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-03-01",
    category: "AML/P",
  },
  {
    name: "Alice Johnson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-04-01",
    category: "AML/P",
  },
  {
    name: "Charlie Brown",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-05-01",
    category: "AML/P",
  },
  {
    name: "Eva Martinez",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-06-01",
    category: "AML/P",
  },
  {
    name: "David Wilson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-07-01",
    category: "AML/P",
  },
  {
    name: "Grace Lee",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-08-01",
    category: "AML/P",
  },
  {
    name: "Frank Adams",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-09-01",
    category: "AML/P",
  },
  {
    name: "Sophie Turner",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-10-01",
    category: "AML/P",
  },
  {
    name: "Alice Johnson",
    type: "Criminal Watch List",
    body: "GAFILAT",
    createdAt: "2022-04-01",
    category: "AML/P",
  },
];
</script>
